codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # basic
        target: "90%"
        threshold: "5%"
        base: auto
        # advanced
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        paths: all
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files"
  behavior: once
  require_changes: false  # if true: only post the comment if coverage changes
