version: '3.2'
services:
  irc:
    init: true
    image: theunkn0wn1/unrealircd
    ports:
      - "6667:6667"
      - "6697:6697"

  services:
    init: true
    image: theunkn0wn1/anope_services

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - .volumes/db_data/:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
