version: 2
jobs:
  build:
    working_directory: ~/repo
    
    docker:
      - image: circleci/python:3.6.5
    
    steps:

      - checkout
      - setup_remote_docker
      - run:
          name: acquire coverage-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      
      - run:
          name: Build containers
          command: |
            docker-compose build
            docker volume create --name=p-data
            docker volume create --name=test-data
            docker-compose up --no-start tests
            docker cp ./config/ spark:/mechasqueak/
      - run:
          name: Run tests
          command: |
            docker-compose up -d sql
            ./cc-test-reporter before-build
            docker-compose up tests
      - run:
          name: Copy workdir from docker container and upload reports
          environment:
            - CC_TEST_REPORTER_ID: c9ec35db75642b31c9d4d818e9efae69202fc4f2a0c2bb35f56ebeef28c4031f
          command: |
            docker cp spark-tests:/test-data/coverage.xml ./
            docker cp spark-tests:/mechasqueak/test-reports ./
            cd mecha
            ./cc-test-reporter after-build --coverage-input-type coverage.py --exit-code $?
      - store_test_results:
          path: test-reports
notify:
  branches:
    - all
  webhooks:
    - url: http://orthanc.localecho.net/cgi-bin/webhook.py
