[irc]
nickname = "Mechasqueak3-tests[BOT]"
server = "localhost"
port = 6697
tls = true
channels = [ "#unkn0wndev",]

[authentication]
method = "PLAIN"

[logging]
base_logger = "testmecha"
log_file = "logs/unit_tests.log"

[database]
host = "localhost"
port = 5432
dbname = "mecha3"
username = "mecha3"
password = "mecha3"
fact_table = "fact"
fact_log = "fact_transaction"

[commands]
prefix = "!"

[api]
online_mode = false
url = "http://localhost/"

[system_api]
url = "https://system.api.fuelrats.com/"

[ratsignal_parser]
announcer_nicks = [ "RatMama[Bot]", "some_announcer", 'unknown' ]

[authentication.plain]
username = ""
password = ""
identity = ""

[authentication.external]
tls_client_cert = "file"

[permissions.recruit]
vhosts = [ "recruit.fuelrats.com",]
level = 0

[permissions.rat]
vhosts = [ "rat.fuelrats.com",]
level = 1

[permissions.overseer]
vhosts = [ "overseer.fuelrats.com",]
level = 2

[permissions.techrat]
vhosts = [ "techrat.fuelrats.com",]
level = 3

[permissions.administrator]
vhosts = [ "op.fuelrats.com", "netadmin.fuelrats.com", "admin.fuelrats.com", "i.see.all",]
level = 4

[board]
cycle_at = 15
api_url = "https://api.thehellisthis.com"